# Generated by Django 5.1.2 on 2024-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
