# Generated by Django 5.1.2 on 2024-10-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_problem_description_problem_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
    ]
