# Generated by Django 5.1.2 on 2024-10-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_problem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solved',
        ),
        migrations.AddField(
            model_name='problem',
            name='solved_by',
            field=models.ManyToManyField(blank=True, to='dashboard.team'),
        ),
    ]
